spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    publisher-returns: true
    publisher-confirms: true
    listener:
      simple:
        retry:
          enabled: true #开启消费者重试
          max-attempts: 5 #最大重试次数
          initial-interval: 2000 #重试间隔时间（单位毫秒）
        default-requeue-rejected: false
      direct:
        acknowledge-mode: manual
server:
  port: 8899

